# Generated by Django 4.1 on 2022-10-29 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_serviceproviders'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviders',
            name='Service',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='community.services'),
            preserve_default='True',
        ),
    ]
