# Generated by Django 4.1 on 2022-10-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_serviceproviders_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Query', models.TextField()),
                ('QueriesAnswer', models.TextField()),
                ('Service_provide', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='community.serviceproviders')),
            ],
        ),
    ]
