# Generated by Django 4.1 on 2022-10-29 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_queryanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Query', models.TextField()),
                ('Category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='community.categories')),
                ('Service', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='community.services')),
                ('Service_provider', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='community.serviceproviders')),
            ],
        ),
    ]
