# Generated by Django 4.1.2 on 2022-10-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviders',
            name='Service',
            field=models.CharField(max_length=200, null='True'),
        ),
    ]
