# Generated by Django 4.1 on 2022-10-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_serviceproviders_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviders',
            name='Service',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='community.services'),
        ),
    ]
