# Generated by Django 4.1 on 2022-10-30 18:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0008_alter_serviceproviders_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.TextField()),
                ('Timestamp', models.DateTimeField(default=datetime.datetime(2022, 10, 30, 18, 6, 48, 858498, tzinfo=datetime.timezone.utc))),
                ('Reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.comment')),
            ],
        ),
        migrations.RemoveField(
            model_name='queryanswer',
            name='Service_provide',
        ),
        migrations.AlterField(
            model_name='serviceproviders',
            name='Service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.services'),
        ),
        migrations.DeleteModel(
            name='Queries',
        ),
        migrations.DeleteModel(
            name='QueryAnswer',
        ),
        migrations.AddField(
            model_name='comment',
            name='Service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.serviceproviders'),
        ),
        migrations.AddField(
            model_name='comment',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
