# Generated by Django 4.1 on 2022-10-31 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 14, 43, 20, 264215, tzinfo=datetime.timezone.utc)),
        ),
    ]
