# Generated by Django 4.1 on 2022-10-31 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_alter_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Reply',
        ),
        migrations.AlterField(
            model_name='comment',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 17, 33, 54, 222590, tzinfo=datetime.timezone.utc)),
        ),
    ]
