# Generated by Django 4.1 on 2022-10-31 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_remove_comment_reply_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 17, 35, 0, 575751, tzinfo=datetime.timezone.utc)),
        ),
    ]
