# Generated by Django 4.1 on 2022-10-31 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_alter_comment_service_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 19, 13, 31, 732771, tzinfo=datetime.timezone.utc)),
        ),
    ]
