# Generated by Django 4.1 on 2022-11-21 18:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 18, 14, 42, 475802, tzinfo=datetime.timezone.utc)),
        ),
    ]
