# Generated by Django 4.1 on 2022-11-23 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_comment_reply_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviders',
            name='Cover_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 16, 47, 21, 489899, tzinfo=datetime.timezone.utc)),
        ),
    ]
